// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsApi.Infrastructure.Data;

#nullable disable

namespace Onyx.Product.Infrastructure.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    partial class ProductsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Onyx.Products.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColourId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PriceId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColourId = 1,
                            ModelId = 1,
                            Name = "iPhone",
                            PriceId = 1
                        },
                        new
                        {
                            Id = 2,
                            ColourId = 2,
                            ModelId = 2,
                            Name = "iPhone",
                            PriceId = 2
                        },
                        new
                        {
                            Id = 3,
                            ColourId = 3,
                            ModelId = 3,
                            Name = "Samsung Flip",
                            PriceId = 3
                        },
                        new
                        {
                            Id = 4,
                            ColourId = 1,
                            ModelId = 4,
                            Name = "Google Pixel",
                            PriceId = 4
                        },
                        new
                        {
                            Id = 5,
                            ColourId = 1,
                            ModelId = 5,
                            Name = "Google Pixel Pro",
                            PriceId = 5
                        },
                        new
                        {
                            Id = 6,
                            ColourId = 3,
                            ModelId = 6,
                            Name = "Google Pixel Mini",
                            PriceId = 6
                        });
                });

            modelBuilder.Entity("Onyx.Products.Domain.Entities.ProductColour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductColours");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColourName = "Red"
                        },
                        new
                        {
                            Id = 2,
                            ColourName = "Blue"
                        },
                        new
                        {
                            Id = 3,
                            ColourName = "Yellow"
                        });
                });

            modelBuilder.Entity("Onyx.Products.Domain.Entities.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelName = "iPhone 15 Pro"
                        },
                        new
                        {
                            Id = 2,
                            ModelName = "iPhone 15 Pro Max"
                        },
                        new
                        {
                            Id = 3,
                            ModelName = "Samsung Z Flip"
                        },
                        new
                        {
                            Id = 4,
                            ModelName = "Google Pixel 10"
                        },
                        new
                        {
                            Id = 5,
                            ModelName = "Google Pixel Pro"
                        },
                        new
                        {
                            Id = 6,
                            ModelName = "Google Pixel 10 Mini"
                        });
                });

            modelBuilder.Entity("Onyx.Products.Domain.Entities.ProductPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000.0m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1199.99m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 800.0m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800.0m
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1800.0m
                        },
                        new
                        {
                            Id = 6,
                            Amount = 800.0m
                        });
                });

            modelBuilder.Entity("Onyx.Products.Domain.Entities.Product", b =>
                {
                    b.HasOne("Onyx.Products.Domain.Entities.ProductColour", "Colour")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Onyx.Products.Domain.Entities.ProductModel", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Onyx.Products.Domain.Entities.ProductPrice", "Price")
                        .WithMany()
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colour");

                    b.Navigation("Model");

                    b.Navigation("Price");
                });
#pragma warning restore 612, 618
        }
    }
}
